### ISSUE TITLE
Problem with project build on OSX

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#58]
Config:

> node     8.1.2
> npm      5.0.3
> nan       2.6.2
> python 2.7.12
> Apple LLVM version 8.1.0 (clang-802.0.42)

After build lib/typescript/master I try build AssemblyScript by ```npm run build```

But crash on this moment:

```bash
npm run build

> assemblyscript@0.0.1 build /Volumes/Archive/Projects/Github/AssemblyScript
> npm run lint && npm run build:check && npm run build:malloc && npm run build:typescript && npm run build:loader && npm run build:library && npm run build:bundle

> assemblyscript@0.0.1 lint /Volumes/Archive/Projects/Github/AssemblyScript
> tslint --config tslint.json src/**/*.ts cli/**/*.ts assembly.d.ts

> assemblyscript@0.0.1 build:check /Volumes/Archive/Projects/Github/AssemblyScript
> node scripts/build-check

It seems that clang is not working on this platform:

  Error: spawn EACCES
    at exports._errnoException (util.js:1016:11)
    at ChildProcess.spawn (internal/child_process.js:317:11)
    at Object.exports.spawn (child_process.js:491:9)
    at /Volumes/Archive/Projects/Github/AssemblyScript/node_modules/webassembly/cli/util.js:33:34
    at Promise (<anonymous>)
    at Object.run (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/webassembly/cli/util.js:32:12)
    at Object.<anonymous> (/Volumes/Archive/Projects/Github/AssemblyScript/scripts/build-check.js:43:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

  Make sure that the webassembly package is properly installed:

  $> npm install webassembly
  
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assemblyscript@0.0.1 build:check: `node scripts/build-check`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the assemblyscript@0.0.1 build:check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2017-06-21T00_11_23_019Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assemblyscript@0.0.1 build: `npm run lint && npm run build:check && npm run build:malloc && npm run build:typescript && npm run build:loader && npm run build:library && npm run build:bundle`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the assemblyscript@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2017-06-21T00_11_23_036Z-debug.log
```

So problem with assemblyscript or wrong current clang version?

**Comment by MaxGraey** [comment]
Resolved
