### ISSUE TITLE
Last update broken dynamic loading assemblyscript

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#62]
window.assemblyscript is undefined right now=(

**Comment by dcodeIO** [comment]
The dist file name has changed from `assemblyscript.min.js` to just `assemblyscript.js`.

**Comment by MaxGraey** [comment]
I try assemblyscript.js as well. Same behaviour

**Comment by dcodeIO** [comment]
Strange, it's working in the assemblyscript playground

**Comment by MaxGraey** [comment]
Yes, by using dynamic script main object sholut manually set to global or window scope. Or use webpack config with:

```js
return {
    ...
    output: {
       ...
       output: {
          libraryTarget: "var"
       }
    }
}
```

**Comment by MaxGraey** [comment]
I try:

```js
require.config({
                            paths: {
                                'assemblyscript': 'https://rawgit.com/dcodeIO/AssemblyScript/master/dist/assemblyscript.js'
                            }
                        });

                        require(['assemblyscript'], () => {
                            console.log('assemblyscript');
                        });
```

But this doesn't work for me

**Comment by dcodeIO** [comment]
Just googled this and found that the `paths` config might have to exclude the extension.

**Comment by MaxGraey** [comment]
I tried this as well. Even:
```js
require.config({
    paths: {
        'assemblyscript': 'https://rawgit.com/dcodeIO/AssemblyScript/master/dist/assemblyscript'
    }
});

require(['async!assemblyscript'], data => {
    console.log('assemblyscript', data);
});
```

Path can't resolve

**Comment by MaxGraey** [comment]
one of creator webpack **sokra** recommend [```scriptjs``` for remote loading](https://github.com/webpack/webpack/issues/240#issuecomment-40686135). But scriptjs pretty old and not compatible with latest AMD.

**Comment by MaxGraey** [comment]
binaryen.ts:
<img width="672" alt="2017-06-24 12 15 45" src="https://user-images.githubusercontent.com/1301959/27507389-e7040f38-58d6-11e7-9cdf-31d1a2b91a2d.png">

I'm still trying to figure it out. If webpack revert to ```libraryTarget: "var"``` as was. We catch this error. It seems problem with resolving binaryen module

**Comment by dcodeIO** [comment]
That's actually one of the reasons why I am not a huge fan of webpack. In general, huge libs like these tend to fall apart as soon as things become a bit more complex.

I investigated this a bit, and, unless I missed some super secret documentation, it also seems that the UMD wrapper code generated by webpack is entirely broken. It calls `require` with `void 0` and stuff like that.

I will try to revert to a `var` target while using and wrapping `require` instead of imports for external dependencies, but this will most likely not work well considering that TypeScript core components are included as-is.

**Comment by MaxGraey** [comment]
Are you tried Webpack 3.0 with ModuleConcatenationPlugin? Developers promise improved [scope hoisting](https://github.com/webpack/webpack/tree/master/examples/scope-hoisting) which should resolve some issue with browsers. But uglify now separate module npm install, so ```uglifyjs-webpack-plugin --save-dev```

**Comment by MaxGraey** [comment]
Hmm, if in tsconfig specify module as "umd", we catch this:

<details><summary>Unroll me</summary><p>
```bash
WARNING in ./src/index.ts
21:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/builtins.ts
11:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/library.ts
7:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/reflection.ts
8:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/statements.ts
8:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/wabt.ts
10:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions.ts
8:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/reflection/class.ts
14:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/reflection/function.ts
14:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/reflection/property.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/reflection/type.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/reflection/variable.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/reflection/enum.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/statements/block.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/statements/break.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/statements/do.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/statements/empty.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/statements/for.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/statements/if.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/statements/return.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/statements/switch.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/statements/variable.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/statements/while.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/statements/expression.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/as.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/binary.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/call.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/conditional.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/elementaccess.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/identifier.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/literal.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/new.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/parenthesized.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/postfixunary.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/prefixunary.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/propertyaccess.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/helpers/store.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./src/expressions/helpers/load.ts
4:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

ERROR in ./src/typescript.ts
(14,21): error TS2307: Cannot find module '../lib/typescript/build'.

ERROR in ./src/typescript.ts
(126,27): error TS7006: Parameter 'fileName' implicitly has an 'any' type.

ERROR in ./src/profiler.ts
(3,22): error TS2307: Cannot find module 'performance-now'.

ERROR in ./src/compiler.ts
(3,25): error TS2307: Cannot find module '@protobufjs/base64'.

ERROR in ./src/binaryen.ts
(16,1): error TS2303: Circular definition of import alias 'none'.

ERROR in ./src/binaryen.ts
(17,1): error TS2303: Circular definition of import alias 'i32'.

ERROR in ./src/binaryen.ts
(18,1): error TS2303: Circular definition of import alias 'i64'.

ERROR in ./src/binaryen.ts
(19,1): error TS2303: Circular definition of import alias 'f32'.

ERROR in ./src/binaryen.ts
(20,1): error TS2303: Circular definition of import alias 'f64'.

ERROR in ./src/binaryen.ts
(21,1): error TS2303: Circular definition of import alias 'Type'.

ERROR in ./src/binaryen.ts
(22,1): error TS2303: Circular definition of import alias 'Signature'.

ERROR in ./src/binaryen.ts
(23,1): error TS2303: Circular definition of import alias 'Function'.

ERROR in ./src/binaryen.ts
(24,1): error TS2303: Circular definition of import alias 'Expression'.

ERROR in ./src/binaryen.ts
(25,1): error TS2303: Circular definition of import alias 'Statement'.

ERROR in ./src/binaryen.ts
(26,1): error TS2303: Circular definition of import alias 'MemorySegment'.

ERROR in ./src/binaryen.ts
(27,1): error TS2303: Circular definition of import alias 'Module'.

ERROR in ./src/binaryen.ts
(28,1): error TS2303: Circular definition of import alias 'I32Expression'.

ERROR in ./src/binaryen.ts
(29,1): error TS2303: Circular definition of import alias 'I64Expression'.

ERROR in ./src/binaryen.ts
(30,1): error TS2303: Circular definition of import alias 'F32Expression'.

ERROR in ./src/binaryen.ts
(31,1): error TS2303: Circular definition of import alias 'F64Expression'.

ERROR in ./src/binaryen.ts
(32,1): error TS2303: Circular definition of import alias 'I32Operations'.

ERROR in ./src/binaryen.ts
(33,1): error TS2303: Circular definition of import alias 'I64Operations'.

ERROR in ./src/binaryen.ts
(34,1): error TS2303: Circular definition of import alias 'F32Operations'.

ERROR in ./src/binaryen.ts
(35,1): error TS2303: Circular definition of import alias 'F64Operations'.

ERROR in ./src/binaryen.ts
(36,1): error TS2303: Circular definition of import alias 'readBinary'.

ERROR in ./src/binaryen.ts
Module build failed: Error: Typescript emitted no output for /Volumes/Archive/Projects/Github/AssemblyScript/src/binaryen.ts.
    at Object.loader (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/ts-loader/dist/index.js:32:15)
 @ ./src/index.ts 25:8-191

ERROR in ./src/compiler.ts
Module build failed: Error: Typescript emitted no output for /Volumes/Archive/Projects/Github/AssemblyScript/src/compiler.ts.
    at Object.loader (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/ts-loader/dist/index.js:32:15)
 @ ./src/index.ts 25:8-191

ERROR in ./src/profiler.ts
Module build failed: Error: Typescript emitted no output for /Volumes/Archive/Projects/Github/AssemblyScript/src/profiler.ts.
    at Object.loader (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/ts-loader/dist/index.js:32:15)
 @ ./src/index.ts 25:8-191

ERROR in ./src/typescript.ts
Module build failed: Error: Typescript emitted no output for /Volumes/Archive/Projects/Github/AssemblyScript/src/typescript.ts.
    at Object.loader (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/ts-loader/dist/index.js:32:15)
 @ ./src/index.ts 25:8-191
```

**Comment by dcodeIO** [comment]
This should be sorted now. For reference, see the check files at https://github.com/dcodeIO/AssemblyScript/tree/master/dist

**Comment by MaxGraey** [comment]
Thanks, nut It seems in my case it still not valid=( By the way if I attach wabt script, I catch this:

<img width="1011" alt="2017-06-25 01 46 06" src="https://user-images.githubusercontent.com/1301959/27512444-7e2be752-5948-11e7-8a1b-512be0f4a460.png">

Never mind. It seems this hard to resolve current time. Don't spend you time to this, currently I include AS into body statically.

**Comment by dcodeIO** [comment]
Iirc monaco-editor's define is not a compatible amd define, so that'd be related solely to monaco-editor.

**Comment by MaxGraey** [comment]
Close, because static scripts using now.
