### ISSUE TITLE
Problem with some build scripts.

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#74]
For npm run build:alldeps
Output: "Missing development dependency: @types/chalk"

But, after installing @types/chalk problem not resolved. Very strange.

Also problem with build bundle:

> tsc -P src && node scripts/build-bundle

module.js:487
    throw err;
    ^

Error: Cannot find module 'path-dirname'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/glob-stream/node_modules/glob-parent/index.js:5:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assemblyscript@0.0.3 build:bundle: `tsc -P src && node scripts/build-bundle`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the assemblyscript@0.0.3 build:bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maxgraey/.npm/_logs/2017-06-30T09_45_58_206Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by dcodeIO** [comment]
For reference: https://github.com/dcodeIO/AssemblyScript/blob/master/scripts/build-check.js#L19

**Comment by MaxGraey** [comment]
Of course I reinstall all packages but this not resolving my issues

**Comment by dcodeIO** [comment]
Does this fix it? Some of the dependencies do not have a `main` file, but are just types.

**Comment by MaxGraey** [comment]
OK, I resolve this. Updated npm to latest 5.0.4 version.
