### ISSUE TITLE
Calling Imported Function Always Fails Validation

### ISSUE THREAD

**Issue by chgibb** [dcodeIO/AssemblyScript#94]
Trying this simple example, adapted from the quickstart:
```
//module.as
export function add(a: int, b: int): int {
  return a + b;
}

let counter : int = 0;

declare function getNext() : int;

export function nextInt() : int {
  getNext();
  return add(1,counter);
}
```
Compiled using:
```
//index.ts
/// <reference types="binaryen" />

import * as fs from "fs";

import {Compiler,CompilerTarget,CompilerMemoryModel,typescript} from "assemblyscript";

let args = process.argv.slice(2);
const moduleSrc = args[0]

const moduleToCompile = Compiler.compileString(
    fs.readFileSync(moduleSrc).toString(),
    {
        target : CompilerTarget.WASM64,
        memoryModel : CompilerMemoryModel.MALLOC,
        silent : true
    }
);

console.error(typescript.formatDiagnostics(Compiler.lastDiagnostics));

if(!moduleToCompile)
    throw Error(`${moduleSrc} compilation failed`);

moduleToCompile.optimize();

if(!moduleToCompile.validate())
    throw Error(`${moduleSrc} validation failed`);

fs.writeFileSync(`${moduleSrc}.wast`,moduleToCompile.emitText());
fs.writeFileSync(`${moduleSrc}.wasm`,moduleToCompile.emitBinary());
```
```
$tsc index.ts
```
Compiling the compiler results in the following under tsc version 2.3.4:
```
node_modules/assemblyscript/dist/assemblyscript.d.ts(52,25): error TS2307: Cannot find module 'long'.
node_modules/assemblyscript/dist/assemblyscript.d.ts(426,23): error TS2307: Cannot find module 'assemblyscript/--/lib/typescript/build'.
node_modules/assemblyscript/dist/assemblyscript.d.ts(1176,24): error TS2304: Cannot find name 'Long'.
node_modules/assemblyscript/dist/assemblyscript.d.ts(1178,99): error TS2304: Cannot find name 'Long'.
```
Though it still produces a Javascript file that appears to work.

Then running:
```
$node index module.as
```
Results in:
```
[wasm-validator error in function $nextInt] unexpected false: call target must exist, on
(call $getNext)
[wasm-validator error in function $.start] 2 != 1: call param types must match, on
[i64] (call $mspace_init
 [i64] (i64.const 8)
)
(on argument 0)

... whole bunch of wast output...

/home/gibb/Desktop/asctesting/test2/node_modules/binaryen/index.js:26
function(e){if(!(e instanceof ha))throw e;});a.inspect=function(){return"[Emscripten Module object]"}}else if(La)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available";},a.readBinary=function(e){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(e));e=read(e,"binary");v("object"===typeof e);return e},"undefined"!=typeof scriptArgs?a.arguments=scriptArgs:"undefined"!=typeof arguments&&(a.arguments=
                                  ^

Error: module.as validation failed
    at Object.<anonymous> (/home/gibb/Desktop/asctesting/test2/index.js:18:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
If I remove the call to the ```declare```d function, it compiles and runs fine. Might be related to [this](https://github.com/WebAssembly/binaryen/issues/1080)

**Comment by dcodeIO** [comment]
Should be fixed in master. The issue here is that binaryen provides both a `call` and a `call_import` operator and older versions (i.e. the one on npm) used the former only.

**Comment by chgibb** [comment]
Hey thanks for the quick reply. Any chance you could release a new version to NPM with the fix? I'm looking to start experimenting with using Assemblyscript to speed up some graph generation, and possibly eventually integrate its use into a project. If I don't have to figure out how to build Assemblyscript on each CI service we're using, and instead just grab it off of NPM, I would be very greatful

**Comment by dcodeIO** [comment]
There is [this outstanding bug](https://github.com/dcodeIO/AssemblyScript/issues/89) currently that I'd like to fix before releasing a new version. Takes longer than expected, unfortunately.

**Comment by chgibb** [comment]
No worries. I just ran into the project last night and started playing, but if there's any specific area you want help in, I'm happy to lend some time.

**Comment by dcodeIO** [comment]
0.2.0 is on npm now

**Comment by chgibb** [comment]
Thanks!
