### ISSUE TITLE
2 != 1: call param types must match

### ISSUE THREAD

**Issue by chgibb** [dcodeIO/AssemblyScript#98]
Given:
```
//module.as

export function add(a: int, b: int): int {
  return a + b;
}

```
Compiled with the compiler mentioned in #94 results in:
```
[wasm-validator error in function $.start] 2 != 1: call param types must match, on
[i64] (call $mspace_init
 [i64] (i64.const 8)
)
(on argument 0)

... Tons of wast...

/home/gibb/Desktop/asctesting/test2/node_modules/assemblyscript/node_modules/binaryen/index.js:26
typeof module&&(module.exports=a);process.on("uncaughtException",function(e){if(!(e instanceof ha))throw e;});a.inspect=function(){return"[Emscripten Module object]"}}else if(La)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available";},a.readBinary=function(e){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(e));e=read(e,"binary");v("object"===typeof e);return e},"undefined"!=typeof scriptArgs?
                                                                                                   ^

Error: module.as validation failed
    at Object.<anonymous> (/home/gibb/Desktop/asctesting/test2/index.js:18:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
Using assmeblyscript@0.2.0,node@8.0.0

**Comment by dcodeIO** [comment]
For some reason it seems that `mspace_init` is called with an i64 instead of an i32. When looking at your compiler, it seems that you are using WASM64, which isn't really supported anywhere, yet. It's mostly there so we can support it once it is, but there isn't a respective runtime, yet.

**Comment by chgibb** [comment]
That fixed it. Thanks!
